# Generated by Django 2.2.9 on 2020-01-17 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='dueTime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
