# Generated by Django 2.2.9 on 2020-01-17 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_task_trashed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='trashed',
            new_name='trash',
        ),
    ]
