# Generated by Django 2.2.9 on 2020-01-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_auto_20200117_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='trash',
            field=models.BooleanField(default=False),
        ),
    ]
