# Generated by Django 2.2.9 on 2020-01-18 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0007_auto_20200118_0443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='Description',
            new_name='description',
        ),
    ]
