# Generated by Django 2.2.9 on 2020-01-18 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0008_auto_20200118_0446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='active',
            new_name='completed',
        ),
    ]
