# Generated by Django 2.2.9 on 2020-01-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0011_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
